version: '3.8'

services:
  app:
    build: .
    container_name: flightstats_app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    container_name: flightstats_celery
    command: sh -c "celery -A main.celery_app worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: flightstats_redis
    ports:
      - "6379:6379"
